### ISSUE TITLE
Horizontal scroll bar is not showing up when vertical scroll bar is at top

### ISSUE THREAD

**Issue by jcubic** [zachleat/selecthor#1]
If the html width is larger then the page there is vertical scrollbar at bottom but it's not showing up untill you scroll to the bottom of the page.

The fix is to add:
```css
.hljs {
    overflow-x: initial;
}
```
 to overwrite style added by `agate.min.css`
